spring:
  application:
    name: dio-speech-ai

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

whisper:
  base-url: http://localhost:8000
  model: Systran/faster-whisper-small

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
 
  endpoint:
    health:
      show-details: always
 
  metrics:
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      percentiles:
        '[http.server.requests]': 0.5, 0.95, 0.99
 
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    '[com.example.diospeechai]': DEBUG	